<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XLSight\XLSight.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="MiniExcel" />
    <PackageReference Include="ExcelDataReader" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../tests/XLSight.Tests/TestData/*.xlsx">
      <Link>TestData\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
